---
# Windows Update Playbook 
# Mustafa KALAYCI @Hikmet Bilgisayar
# V 1.02 | 28.11.24

# Sample runing command: 
# ansible-playbook -i inventory/xxx_hosts.yml win_upd_pbook.yml -e 'cust=HKN target=LOG fw=log' --ask-vault-password
# fw=for  : Fortinet
# fw=snc  : Sonicwall

#--------------------------------------------------------------
#---------------------------VPN--------------------------------
#--------------------------------------------------------------


- name: VPN Bağlantısı kur
  hosts: localhost
  gather_facts: no
  become: yes

  vars_files:
    - ./roles/{{ fw }}_vpnConnect/vars/{{ cust }}_vpn.yml 

  roles:
    - "{{ fw }}_vpnConnect"  


#--------------------------------------------------------------
#--------------------WINDOWS HOSTLAR---------------------------
#--------------------------------------------------------------


- name: MÜŞTERİ Windows Hostlar için Görevler
  hosts: "{{ target }}"
  gather_facts: no
#  become: yes

  vars:
    target_date: "28/02/2026"  # Sabit format (DD/MM/YYYY)
    target_time: "02:30"       # Sabit saat formatı
  
  roles:
    #  -------- Windows Opersayonları ------------  
    
    - gen_winPing       # Windows Makinaya Ping Atar
    - win_WinUpdSecCrt  # Windows Critical, Sec. ve Rollup Update (reboot gerekirse takvimler)
    #- win_schReboot     # Belirtilen Zamana(reboot_time) tek seferlik Reboot Task oluşturur.
  
    



#--------------------------------------------------------------
#---------------------------VPN--------------------------------
#--------------------------------------------------------------


- name:  VPN sonlandır
  hosts: localhost
  gather_facts: no
  become: yes

  roles:
    - "{{ fw }}_vpnTerminate"  
