---
# Windows Test Playbook 
# Mustafa KALAYCI @Hikmet Bilgisayar
# V 1.01 | 15/03/2026

# Sample runing command: 
# ansible-playbook win_test_pbook.yml -i inventory/xxx_hosts.yml --limit "THOST" -e "target=THOST" --vault-password-file .vault_pass

#--------------------------------------------------------------
#--------------------WINDOWS HOSTLAR---------------------------
#--------------------------------------------------------------



- name: MÜŞTERİ Windows Hostlar için Görevler
  hosts: "{{ target }}"
  gather_facts: yes

  tasks:
    - name: Operasyon Rollerim
      include_role:
        name: "{{ item }}"
      loop:
        - gen_winPing
        - win_WinUpdSecCrt
        #- win_schReboot