---
# Windows Test Playbook 
# Mustafa KALAYCI @Hikmet Bilgisayar
# V 1.0 | 13/03/2026

# Sample runing command: 
# ansible-playbook -i inventory/xxx_hosts.yml win_test_pbook.yml -e 'target=LOG ' --ask-vault-password


#--------------------------------------------------------------
#--------------------WINDOWS HOSTLAR---------------------------
#--------------------------------------------------------------



- name: MÜŞTERİ Windows Hostlar için Görevler
  hosts: "{{ target }}"
  gather_facts: yes

  tasks:
    - name: Hedef Tarihi Hesapla
      set_fact:
        # Değişkenleri doğrudan defaults/main.yml'den çeker
        target_date: "{{ (ansible_date_time.epoch | int + (r_after_days | int * 86400)) | strftime('%d/%m/%Y') }}"
        target_time: "{{ r_time }}"

    - name: Operasyon Rollerim
      include_role:
        name: "{{ item }}"
      loop:
        - gen_winPing
        #- win_WinUpdSecCrt
        - win_schReboot