- name: Degiskenleri Hazirla
  set_fact:
    r_days_val: "{{ r_after_days | default(1) | int }}"
    r_time_val: "{{ r_time | default('03:00') | trim }}"

- name: Tek seferlik reboot görevi oluştur
  ansible.windows.win_shell: |
    $days = [int]{{ r_days_val }}
    $timeInput = "{{ r_time_val }}"

    if ($timeInput -eq "" -or $timeInput -eq "{}") { $timeInput = "03:00" }

    $timeStr = $timeInput
    if ($timeStr -notmatch ':\d{2}:\d{2}$') {
        $timeStr = $timeStr + ":00"
    }

    # TARİH: mm/dd/yyyy
    $dt = (Get-Date).AddDays($days)
    $dateStr = $dt.ToString("MM/dd/yyyy")

    schtasks /delete /tn "Ansible_Reboot" /f 2>$null
    
    schtasks /create /tn "Ansible_Reboot" /tr "shutdown.exe /r /f /t 0" /sc once /sd "$dateStr" /st "$timeStr" /ru SYSTEM /f